# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticket_info.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 423)
        MainWindow.setStyleSheet("/*Copyright (c) DevSec Studio. All rights reserved.\n"
"\n"
"MIT License\n"
"\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to deal\n"
"in the Software without restriction, including without limitation the rights\n"
"to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
"copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in all\n"
"copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
"OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
"*/\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    background-color: #3a3a3a;\n"
"    color: #fff;\n"
"    selection-background-color: #b78620;\n"
"    selection-color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenuBar-----*/\n"
"QMenuBar \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item \n"
"{\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:selected \n"
"{\n"
"    background-color: rgba(183, 134, 32, 20%);\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenuBar::item:pressed \n"
"{\n"
"    background-color: rgb(183, 134, 32);\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QMenu-----*/\n"
"QMenu\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #222;\n"
"    padding: 4px;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item\n"
"{\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::separator\n"
"{\n"
"       background-color: rgb(183, 134, 32);\n"
"    height: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:disabled\n"
"{\n"
"    color: #555;\n"
"    background-color: transparent;\n"
"    padding: 2px 20px 2px 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    background-color: rgba(183, 134, 32, 20%);\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolBar-----*/\n"
"QToolBar\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(69, 69, 69, 255),stop:1 rgba(58, 58, 58, 255));\n"
"    border-top: none;\n"
"    border-bottom: 1px solid #4f4f4f;\n"
"    border-left: 1px solid #4f4f4f;\n"
"    border-right: 1px solid #4f4f4f;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolBar::separator\n"
"{\n"
"    background-color: #2e2e2e;\n"
"    width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton \n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    padding: 5px;\n"
"    padding-left: 8px;\n"
"    padding-right: 8px;\n"
"    margin-left: 1px;\n"
"}\n"
"\n"
"\n"
"QToolButton:hover\n"
"{\n"
"    background-color: rgba(183, 134, 32, 20%);\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"    \n"
"}\n"
"\n"
"\n"
"QToolButton:pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton:checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #222;\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(84, 84, 84, 255),stop:1 rgba(59, 59, 59, 255));\n"
"    color: #ffffff;\n"
"    min-width: 80px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 3px;\n"
"    border-color: #051a39;\n"
"    padding: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::flat\n"
"{\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: rgba(183, 134, 32, 20%);\n"
"    border: 1px solid #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(74, 74, 74, 255),stop:1 rgba(49, 49, 49, 255));\n"
"    border: 1px solid #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(74, 74, 74, 255),stop:1 rgba(49, 49, 49, 255));\n"
"    border: 1px solid #222;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit\n"
"{\n"
"    background-color: #131313;\n"
"    color : #eee;\n"
"    border: 1px solid #343434;\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPlainTExtEdit-----*/\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #131313;\n"
"    color : #eee;\n"
"    border: 1px solid #343434;\n"
"    border-radius: 2px;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTabBar-----*/\n"
"QTabBar::tab\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(84, 84, 84, 255),stop:1 rgba(59, 59, 59, 255));\n"
"    color: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: #666;\n"
"    border-bottom: none;\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabWidget::pane \n"
"{\n"
"    background-color: red;\n"
"    border: 1px solid #666;\n"
"    top: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; \n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
"    background-color: #0c0c0d;\n"
"    margin-left: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    background-color: #0c0c0d;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    margin-bottom: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    border-top-color: #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(84, 84, 84, 255),stop:1 rgba(59, 59, 59, 255));\n"
"    border: 1px solid #000;\n"
"    padding-left: 6px;\n"
"    color: #ffffff;\n"
"    height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::disabled\n"
"{\n"
"    background-color: #404040;\n"
"    color: #656565;\n"
"    border-color: #051a39;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: #b78620;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: #383838;\n"
"    color: #ffffff;\n"
"    border: 1px solid black;\n"
"    selection-background-color: #b78620;\n"
"    outline: 0;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(57, 57, 57, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: black;\n"
"    border-left-style: solid; \n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}\n"
"\n"
"\n"
"/*-----QSpinBox & QDateTimeEdit-----*/\n"
"QSpinBox,\n"
"QDateTimeEdit \n"
"{\n"
"    background-color: #131313;\n"
"    color : #eee;\n"
"    border: 1px solid #343434;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    border-radius : 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button, \n"
"QDateTimeEdit::up-button\n"
"{\n"
"    border-top-right-radius:2px;\n"
"    background-color: #777777;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:hover, \n"
"QDateTimeEdit::up-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-button:pressed, \n"
"QDateTimeEdit::up-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::up-arrow,\n"
"QDateTimeEdit::up-arrow\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button, \n"
"QDateTimeEdit::down-button\n"
"{\n"
"    border-bottom-right-radius:2px;\n"
"    background-color: #777777;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button:hover, \n"
"QDateTimeEdit::down-button:hover\n"
"{\n"
"    background-color: #585858;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-button:pressed, \n"
"QDateTimeEdit::down-button:pressed\n"
"{\n"
"    background-color: #252525;\n"
"    width: 16px; \n"
"    border-width: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox::down-arrow,\n"
"QDateTimeEdit::down-arrow\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 7px;\n"
"    height: 7px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QGroupBox-----*/\n"
"QGroupBox \n"
"{\n"
"    border: 1px solid;\n"
"    border-color: #666666;\n"
"    border-radius: 5px;\n"
"    margin-top: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QGroupBox::title  \n"
"{\n"
"    background-color: transparent;\n"
"    color: #eee;\n"
"    subcontrol-origin: margin;\n"
"    padding: 5px;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QHeaderView-----*/\n"
"QHeaderView::section\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(60, 60, 60, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"    text-align: left;\n"
"    padding: 4px;\n"
"    \n"
"}\n"
"\n"
"\n"
"QHeaderView::section:disabled\n"
"{\n"
"    background-color: #525251;\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section:checked\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(60, 60, 60, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical::first,\n"
"QHeaderView::section::vertical::only-one\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::vertical\n"
"{\n"
"    border-top: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal::first,\n"
"QHeaderView::section::horizontal::only-one\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QHeaderView::section::horizontal\n"
"{\n"
"    border-left: 1px solid #353635;\n"
"\n"
"}\n"
"\n"
"\n"
"QTableCornerButton::section\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(60, 60, 60, 255),stop:1 rgba(50, 50, 50, 255));\n"
"    border: 1px solid #000;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QTreeWidget-----*/\n"
"QTreeView\n"
"{\n"
"    show-decoration-selected: 1;\n"
"    alternate-background-color: #3a3a3a;\n"
"    selection-color: #fff;\n"
"    background-color: #2d2d2d;\n"
"    border: 1px solid gray;\n"
"    padding-top : 5px;\n"
"    color: #fff;\n"
"    font: 8pt;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:selected\n"
"{\n"
"    color:#fff;\n"
"    background-color: #b78620;\n"
"    border-radius: 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::item:!selected:hover\n"
"{\n"
"    background-color: #262626;\n"
"    border: none;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings \n"
"{\n"
"    image: url(://tree-closed.png);\n"
"\n"
"}\n"
"\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  \n"
"{\n"
"    image: url(://tree-open.png);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QListView-----*/\n"
"QListView \n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(83, 83, 83, 255),stop:0.293269 rgba(81, 81, 81, 255),stop:0.634615 rgba(79, 79, 79, 255),stop:1 rgba(83, 83, 83, 255));\n"
"    border : none;\n"
"    color: white;\n"
"    show-decoration-selected: 1; \n"
"    outline: 0;\n"
"    border: 1px solid gray;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::disabled \n"
"{\n"
"    background-color: #656565;\n"
"    color: #1b1b1b;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item \n"
"{\n"
"    background-color: #2d2d2d;\n"
"    padding: 1px;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:alternate \n"
"{\n"
"    background-color: #3a3a3a;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected \n"
"{\n"
"    background-color: #b78620;\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:!active \n"
"{\n"
"    background-color: #b78620;\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:selected:active \n"
"{\n"
"    background-color: #b78620;\n"
"    border: 1px solid #b78620;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QListView::item:hover {\n"
"    background-color: #262626;\n"
"    border: none;\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: lightgray;\n"
"    border: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    background-color: #323232;\n"
"    border: 1px solid darkgray;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\");\n"
"    background-color: #b78620;\n"
"    border: 1px solid #3a546e;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #b78620; \n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QRadioButton-----*/\n"
"QRadioButton \n"
"{\n"
"    color: lightgray;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::unchecked:hover \n"
"{\n"
"    background-color: lightgray;\n"
"    border: 2px solid #b78620;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"\n"
"QRadioButton::indicator::checked \n"
"{\n"
"    border: 2px solid #b78620;\n"
"    border-radius: 6px;\n"
"    background-color: rgba(183,134,32,20%);  \n"
"    width: 9px; \n"
"    height: 9px; \n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QSlider-----*/\n"
"QSlider::groove:horizontal \n"
"{\n"
"    background-color: transparent;\n"
"    height: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    background-color: #b78620;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    background-color: #131313;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background-color: #b78620;\n"
"    width: 14px;\n"
"    margin-top: -6px;\n"
"    margin-bottom: -6px;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:hover \n"
"{\n"
"    background-color: #d89e25;\n"
"    border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::sub-page:horizontal:disabled \n"
"{\n"
"    background-color: #bbb;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::add-page:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border-color: #999;\n"
"\n"
"}\n"
"\n"
"\n"
"QSlider::handle:horizontal:disabled \n"
"{\n"
"    background-color: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 3px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QScrollBar-----*/\n"
"QScrollBar:horizontal\n"
"{\n"
"    border: 1px solid #222222;\n"
"    background-color: #3d3d3d;\n"
"    height: 15px;\n"
"    margin: 0px 16px 0 16px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    width: 15px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    width: 15px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::right-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-right.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::left-arrow:horizontal\n"
"{\n"
"    image: url(://arrow-left.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"    background-color: #3d3d3d;\n"
"    width: 16px;\n"
"    border: 1px solid #2d2d2d;\n"
"    margin: 16px 0px 16px 0px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    min-height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    height: 15px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(97, 97, 97, 255),stop:1 rgba(90, 90, 90, 255));\n"
"    border: 1px solid #2d2d2d;\n"
"    height: 15px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::up-arrow:vertical\n"
"{\n"
"    image: url(://arrow-up.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"    image: url(://arrow-down.png);\n"
"    width: 6px;\n"
"    height: 6px;\n"
"\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"    background: none;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QProgressBar-----*/\n"
"QProgressBar\n"
"{\n"
"    border: 1px solid #666666;\n"
"    text-align: center;\n"
"    color: #000;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #b78620;\n"
"    width: 30px;\n"
"    margin: 0.5px;\n"
"\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 521, 361))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 271, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_report_number = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_report_number.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_report_number.setAutoFillBackground(False)
        self.lineEdit_report_number.setStyleSheet("QLineEdit{\n"
"background-color:rgb(170, 170, 170)\n"
"}\n"
"QToolTip{\n"
"  color:#ffffff;\n"
"  background-color:palette(base);\n"
"  border:1px solid palette(highlight);\n"
"  border-radius:4px;\n"
"}\n"
"QStatusBar{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  color:palette(mid);\n"
"}\n"
"QMenuBar{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-bottom:2px solid rgba(25,25,25,75);\n"
"}\n"
"QMenuBar::item{\n"
"  spacing:2px;\n"
"  padding:3px 4px;\n"
"  background:transparent;\n"
"}\n"
"QMenuBar::item:selected{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(106,106,106,255),stop:1 rgba(106,106,106,75));\n"
"  border-left:1px solid rgba(106,106,106,127);\n"
"  border-right:1px solid rgba(106,106,106,127);\n"
"}\n"
"QMenuBar::item:pressed{\n"
"  background-color:palette(highlight);\n"
"  border-left:1px solid rgba(25,25,25,127);\n"
"  border-right:1px solid rgba(25,25,25,127);\n"
"}\n"
"QMenu{\n"
"  background-color:palette(window);\n"
"  border:1px solid palette(shadow);\n"
"}\n"
"QMenu::item{\n"
"  padding:3px 25px 3px 25px;\n"
"  border:1px solid transparent;\n"
"}\n"
"QMenu::item:disabled{\n"
"  background-color:rgba(35,35,35,127);\n"
"  color:palette(disabled);\n"
"}\n"
"QMenu::item:selected{\n"
"  border-color:rgba(147,191,236,127);\n"
"  background:palette(highlight);\n"
"}\n"
"QMenu::icon:checked{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid palette(highlight);\n"
"  border-radius:2px;\n"
"}\n"
"QMenu::separator{\n"
"  height:1px;\n"
"  background:palette(alternate-base);\n"
"  margin-left:5px;\n"
"  margin-right:5px;\n"
"}\n"
"QMenu::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QMenu::indicator:non-exclusive:checked{\n"
"  image:url(:/darkstyle/icon_checkbox_checked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:non-exclusive:unchecked{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:exclusive:checked{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:exclusive:unchecked{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QToolBar::top{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-bottom:3px solid qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::bottom{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-top:3px solid qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::left{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-right:3px solid qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::right{\n"
"  background-color:qlineargradient(x1:1,y1:0,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-left:3px solid qlineargradient(x1:1,y1:0,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QMainWindow::separator{\n"
"  width:6px;\n"
"  height:5px;\n"
"  padding:2px;\n"
"}\n"
"QSplitter::handle:horizontal{\n"
"  width:10px;\n"
"}\n"
"QSplitter::handle:vertical{\n"
"  height:10px;\n"
"}\n"
"QMainWindow::separator:hover,QSplitter::handle:hover{\n"
"  background:palette(highlight);\n"
"}\n"
"QDockWidget::title{\n"
"  padding:4px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-bottom:2px solid rgba(25,25,25,75);\n"
"}\n"
"QDockWidget{\n"
"  titlebar-close-icon:url(:/darkstyle/icon_close.png);\n"
"  titlebar-normal-icon:url(:/darkstyle/icon_restore.png);\n"
"}\n"
"QDockWidget::close-button,QDockWidget::float-button{\n"
"  subcontrol-position:top right;\n"
"  subcontrol-origin:margin;\n"
"  position:absolute;\n"
"  top:3px;\n"
"  bottom:0px;\n"
"  width:20px;\n"
"  height:20px;\n"
"}\n"
"QDockWidget::close-button{\n"
"  right:3px;\n"
"}\n"
"QDockWidget::float-button{\n"
"  right:25px;\n"
"}\n"
"QGroupBox{\n"
"  background-color:rgba(66,66,66,50%);\n"
"  margin-top:27px;\n"
"  border:1px solid rgba(25,25,25,127);\n"
"  border-radius:4px;\n"
"}\n"
"QGroupBox::title{\n"
"  subcontrol-origin:margin;\n"
"  subcontrol-position:left top;\n"
"  padding:4px 6px;\n"
"  margin-left:3px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-bottom:2px solid rgb(127,127,127);\n"
"  border-top-left-radius:4px;\n"
"  border-top-right-radius:4px;\n"
"}\n"
"QTabWidget::pane{\n"
"  background-color:rgba(66,66,66,50%);\n"
"  border-top:1px solid rgba(25,25,25,50%);\n"
"}\n"
"QTabWidget::tab-bar{\n"
"  left:3px;\n"
"  top:1px;\n"
"}\n"
"QTabBar{\n"
"  background-color:transparent;\n"
"  qproperty-drawBase:0;\n"
"  border-bottom:1px solid rgba(25,25,25,50%);\n"
"}\n"
"QTabBar::tab{\n"
"  padding:4px 6px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-top-left-radius:4px;\n"
"  border-top-right-radius:4px;\n"
"}\n"
"QTabBar::tab:selected,QTabBar::tab:hover{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(53,53,53,127),stop:1 rgba(66,66,66,50%));\n"
"  border-bottom-color:rgba(66,66,66,75%);\n"
"}\n"
"QTabBar::tab:selected{\n"
"  border-bottom:2px solid palette(highlight);\n"
"}\n"
"QTabBar::tab::selected:disabled{\n"
"  border-bottom:2px solid rgb(127,127,127);\n"
"}\n"
"QTabBar::tab:!selected{\n"
"  margin-top:2px;\n"
"}\n"
"QCheckBox::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QCheckBox::indicator:checked,QTreeView::indicator:checked,QTableView::indicator:checked,QGroupBox::indicator:checked{\n"
"  image:url(:/darkstyle/icon_checkbox_checked.png);\n"
"}\n"
"QCheckBox::indicator:checked:pressed,QTreeView::indicator:checked:pressed,QTableView::indicator:checked:pressed,QGroupBox::indicator:checked:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_checked_pressed.png);\n"
"}\n"
"QCheckBox::indicator:checked:disabled,QTreeView::indicator:checked:disabled,QTableView::indicator:checked:disabled,QGroupBox::indicator:checked:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_checked_disabled.png);\n"
"}\n"
"QCheckBox::indicator:unchecked,QTreeView::indicator:unchecked,QTableView::indicator:unchecked,QGroupBox::indicator:unchecked{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked.png);\n"
"}\n"
"QCheckBox::indicator:unchecked:pressed,QTreeView::indicator:unchecked:pressed,QTableView::indicator:unchecked:pressed,QGroupBox::indicator:unchecked:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked_pressed.png);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled,QTreeView::indicator:unchecked:disabled,QTableView::indicator:unchecked:disabled,QGroupBox::indicator:unchecked:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked_disabled.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate,QTreeView::indicator:indeterminate,QTableView::indicator:indeterminate,QGroupBox::indicator:indeterminate{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate:pressed,QTreeView::indicator:indeterminate:pressed,QTableView::indicator:indeterminate:pressed,QGroupBox::indicator:indeterminate:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate_pressed.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate:disabled,QTreeView::indicator:indeterminate:disabled,QTableView::indicator:indeterminate:disabled,QGroupBox::indicator:indeterminate:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate_disabled.png);\n"
"}\n"
"QRadioButton::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked.png);\n"
"}\n"
"QRadioButton::indicator:checked:pressed{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked_pressed.png);\n"
"}\n"
"QRadioButton::indicator:checked:disabled{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked_disabled.png);\n"
"}\n"
"QRadioButton::indicator:unchecked{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked.png);\n"
"}\n"
"QRadioButton::indicator:unchecked:pressed{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked_pressed.png);\n"
"}\n"
"QRadioButton::indicator:unchecked:disabled{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked_disabled.png);\n"
"}\n"
"QTreeView, QTableView{\n"
"  alternate-background-color:palette(window);\n"
"  background:palette(base);\n"
"}\n"
"QTreeView QHeaderView::section, QTableView QHeaderView::section{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-style:none;\n"
"  border-bottom:1px solid palette(dark);\n"
"  padding-left:5px;\n"
"  padding-right:5px;\n"
"}\n"
"QTreeView::item:selected:disabled, QTableView::item:selected:disabled{\n"
"  background:rgb(80,80,80);\n"
"}\n"
"QTreeView::branch{\n"
"  background-color:palette(base);\n"
"}\n"
"QTreeView::branch:has-siblings:!adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_vline.png) 0;\n"
"}\n"
"QTreeView::branch:has-siblings:adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_branch_more.png) 0;\n"
"}\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_branch_end.png) 0;\n"
"}\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings{\n"
"  border-image:none;\n"
"  image:url(:/darkstyle/icon_branch_closed.png);\n"
"}\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings{\n"
"  border-image:none;\n"
"  image:url(:/darkstyle/icon_branch_open.png);\n"
"}\n"
"QScrollBar:vertical{\n"
"  background:palette(base);\n"
"  border-top-right-radius:2px;\n"
"  border-bottom-right-radius:2px;\n"
"  width:16px;\n"
"  margin:0px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"  background-color:palette(alternate-base);\n"
"  border-radius:2px;\n"
"  min-height:20px;\n"
"  margin:2px 4px 2px 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"  background-color:palette(highlight);\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"  background:none;\n"
"  height:0px;\n"
"  subcontrol-position:right;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"  background:none;\n"
"  height:0px;\n"
"  subcontrol-position:left;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar:horizontal{\n"
"  background:palette(base);\n"
"  height:16px;\n"
"  margin:0px;\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"  background-color:palette(alternate-base);\n"
"  border-radius:2px;\n"
"  min-width:20px;\n"
"  margin:4px 2px 4px 2px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"  background-color:palette(highlight);\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"  background:none;\n"
"  width:0px;\n"
"  subcontrol-position:bottom;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"  background:none;\n"
"  width:0px;\n"
"  subcontrol-position:top;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QSlider::handle:horizontal{\n"
"  border-radius:4px;\n"
"  border:1px solid rgba(25,25,25,255);\n"
"  background-color:palette(alternate-base);\n"
"  min-height:20px;\n"
"  margin:0 -4px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"  background:palette(highlight);\n"
"}\n"
"QSlider::add-page:horizontal{\n"
"  background:palette(base);\n"
"}\n"
"QSlider::sub-page:horizontal{\n"
"  background:palette(highlight);\n"
"}\n"
"QSlider::sub-page:horizontal:disabled{\n"
"  background:rgb(80,80,80);\n"
"}")
        self.lineEdit_report_number.setObjectName("lineEdit_report_number")
        self.horizontalLayout_4.addWidget(self.lineEdit_report_number)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label1.setAutoFillBackground(False)
        self.label1.setObjectName("label1")
        self.horizontalLayout.addWidget(self.label1)
        self.lineEdit_license_plate = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_license_plate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_license_plate.setAutoFillBackground(False)
        self.lineEdit_license_plate.setStyleSheet("QLineEdit{\n"
"background-color:rgb(170, 170, 170)\n"
"}\n"
"QToolTip{\n"
"  color:#ffffff;\n"
"  background-color:palette(base);\n"
"  border:1px solid palette(highlight);\n"
"  border-radius:4px;\n"
"}\n"
"QStatusBar{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  color:palette(mid);\n"
"}\n"
"QMenuBar{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-bottom:2px solid rgba(25,25,25,75);\n"
"}\n"
"QMenuBar::item{\n"
"  spacing:2px;\n"
"  padding:3px 4px;\n"
"  background:transparent;\n"
"}\n"
"QMenuBar::item:selected{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(106,106,106,255),stop:1 rgba(106,106,106,75));\n"
"  border-left:1px solid rgba(106,106,106,127);\n"
"  border-right:1px solid rgba(106,106,106,127);\n"
"}\n"
"QMenuBar::item:pressed{\n"
"  background-color:palette(highlight);\n"
"  border-left:1px solid rgba(25,25,25,127);\n"
"  border-right:1px solid rgba(25,25,25,127);\n"
"}\n"
"QMenu{\n"
"  background-color:palette(window);\n"
"  border:1px solid palette(shadow);\n"
"}\n"
"QMenu::item{\n"
"  padding:3px 25px 3px 25px;\n"
"  border:1px solid transparent;\n"
"}\n"
"QMenu::item:disabled{\n"
"  background-color:rgba(35,35,35,127);\n"
"  color:palette(disabled);\n"
"}\n"
"QMenu::item:selected{\n"
"  border-color:rgba(147,191,236,127);\n"
"  background:palette(highlight);\n"
"}\n"
"QMenu::icon:checked{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid palette(highlight);\n"
"  border-radius:2px;\n"
"}\n"
"QMenu::separator{\n"
"  height:1px;\n"
"  background:palette(alternate-base);\n"
"  margin-left:5px;\n"
"  margin-right:5px;\n"
"}\n"
"QMenu::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QMenu::indicator:non-exclusive:checked{\n"
"  image:url(:/darkstyle/icon_checkbox_checked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:non-exclusive:unchecked{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:exclusive:checked{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:exclusive:unchecked{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QToolBar::top{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-bottom:3px solid qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::bottom{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-top:3px solid qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::left{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-right:3px solid qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::right{\n"
"  background-color:qlineargradient(x1:1,y1:0,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-left:3px solid qlineargradient(x1:1,y1:0,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QMainWindow::separator{\n"
"  width:6px;\n"
"  height:5px;\n"
"  padding:2px;\n"
"}\n"
"QSplitter::handle:horizontal{\n"
"  width:10px;\n"
"}\n"
"QSplitter::handle:vertical{\n"
"  height:10px;\n"
"}\n"
"QMainWindow::separator:hover,QSplitter::handle:hover{\n"
"  background:palette(highlight);\n"
"}\n"
"QDockWidget::title{\n"
"  padding:4px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-bottom:2px solid rgba(25,25,25,75);\n"
"}\n"
"QDockWidget{\n"
"  titlebar-close-icon:url(:/darkstyle/icon_close.png);\n"
"  titlebar-normal-icon:url(:/darkstyle/icon_restore.png);\n"
"}\n"
"QDockWidget::close-button,QDockWidget::float-button{\n"
"  subcontrol-position:top right;\n"
"  subcontrol-origin:margin;\n"
"  position:absolute;\n"
"  top:3px;\n"
"  bottom:0px;\n"
"  width:20px;\n"
"  height:20px;\n"
"}\n"
"QDockWidget::close-button{\n"
"  right:3px;\n"
"}\n"
"QDockWidget::float-button{\n"
"  right:25px;\n"
"}\n"
"QGroupBox{\n"
"  background-color:rgba(66,66,66,50%);\n"
"  margin-top:27px;\n"
"  border:1px solid rgba(25,25,25,127);\n"
"  border-radius:4px;\n"
"}\n"
"QGroupBox::title{\n"
"  subcontrol-origin:margin;\n"
"  subcontrol-position:left top;\n"
"  padding:4px 6px;\n"
"  margin-left:3px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-bottom:2px solid rgb(127,127,127);\n"
"  border-top-left-radius:4px;\n"
"  border-top-right-radius:4px;\n"
"}\n"
"QTabWidget::pane{\n"
"  background-color:rgba(66,66,66,50%);\n"
"  border-top:1px solid rgba(25,25,25,50%);\n"
"}\n"
"QTabWidget::tab-bar{\n"
"  left:3px;\n"
"  top:1px;\n"
"}\n"
"QTabBar{\n"
"  background-color:transparent;\n"
"  qproperty-drawBase:0;\n"
"  border-bottom:1px solid rgba(25,25,25,50%);\n"
"}\n"
"QTabBar::tab{\n"
"  padding:4px 6px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-top-left-radius:4px;\n"
"  border-top-right-radius:4px;\n"
"}\n"
"QTabBar::tab:selected,QTabBar::tab:hover{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(53,53,53,127),stop:1 rgba(66,66,66,50%));\n"
"  border-bottom-color:rgba(66,66,66,75%);\n"
"}\n"
"QTabBar::tab:selected{\n"
"  border-bottom:2px solid palette(highlight);\n"
"}\n"
"QTabBar::tab::selected:disabled{\n"
"  border-bottom:2px solid rgb(127,127,127);\n"
"}\n"
"QTabBar::tab:!selected{\n"
"  margin-top:2px;\n"
"}\n"
"QCheckBox::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QCheckBox::indicator:checked,QTreeView::indicator:checked,QTableView::indicator:checked,QGroupBox::indicator:checked{\n"
"  image:url(:/darkstyle/icon_checkbox_checked.png);\n"
"}\n"
"QCheckBox::indicator:checked:pressed,QTreeView::indicator:checked:pressed,QTableView::indicator:checked:pressed,QGroupBox::indicator:checked:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_checked_pressed.png);\n"
"}\n"
"QCheckBox::indicator:checked:disabled,QTreeView::indicator:checked:disabled,QTableView::indicator:checked:disabled,QGroupBox::indicator:checked:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_checked_disabled.png);\n"
"}\n"
"QCheckBox::indicator:unchecked,QTreeView::indicator:unchecked,QTableView::indicator:unchecked,QGroupBox::indicator:unchecked{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked.png);\n"
"}\n"
"QCheckBox::indicator:unchecked:pressed,QTreeView::indicator:unchecked:pressed,QTableView::indicator:unchecked:pressed,QGroupBox::indicator:unchecked:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked_pressed.png);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled,QTreeView::indicator:unchecked:disabled,QTableView::indicator:unchecked:disabled,QGroupBox::indicator:unchecked:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked_disabled.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate,QTreeView::indicator:indeterminate,QTableView::indicator:indeterminate,QGroupBox::indicator:indeterminate{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate:pressed,QTreeView::indicator:indeterminate:pressed,QTableView::indicator:indeterminate:pressed,QGroupBox::indicator:indeterminate:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate_pressed.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate:disabled,QTreeView::indicator:indeterminate:disabled,QTableView::indicator:indeterminate:disabled,QGroupBox::indicator:indeterminate:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate_disabled.png);\n"
"}\n"
"QRadioButton::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked.png);\n"
"}\n"
"QRadioButton::indicator:checked:pressed{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked_pressed.png);\n"
"}\n"
"QRadioButton::indicator:checked:disabled{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked_disabled.png);\n"
"}\n"
"QRadioButton::indicator:unchecked{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked.png);\n"
"}\n"
"QRadioButton::indicator:unchecked:pressed{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked_pressed.png);\n"
"}\n"
"QRadioButton::indicator:unchecked:disabled{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked_disabled.png);\n"
"}\n"
"QTreeView, QTableView{\n"
"  alternate-background-color:palette(window);\n"
"  background:palette(base);\n"
"}\n"
"QTreeView QHeaderView::section, QTableView QHeaderView::section{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-style:none;\n"
"  border-bottom:1px solid palette(dark);\n"
"  padding-left:5px;\n"
"  padding-right:5px;\n"
"}\n"
"QTreeView::item:selected:disabled, QTableView::item:selected:disabled{\n"
"  background:rgb(80,80,80);\n"
"}\n"
"QTreeView::branch{\n"
"  background-color:palette(base);\n"
"}\n"
"QTreeView::branch:has-siblings:!adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_vline.png) 0;\n"
"}\n"
"QTreeView::branch:has-siblings:adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_branch_more.png) 0;\n"
"}\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_branch_end.png) 0;\n"
"}\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings{\n"
"  border-image:none;\n"
"  image:url(:/darkstyle/icon_branch_closed.png);\n"
"}\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings{\n"
"  border-image:none;\n"
"  image:url(:/darkstyle/icon_branch_open.png);\n"
"}\n"
"QScrollBar:vertical{\n"
"  background:palette(base);\n"
"  border-top-right-radius:2px;\n"
"  border-bottom-right-radius:2px;\n"
"  width:16px;\n"
"  margin:0px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"  background-color:palette(alternate-base);\n"
"  border-radius:2px;\n"
"  min-height:20px;\n"
"  margin:2px 4px 2px 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"  background-color:palette(highlight);\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"  background:none;\n"
"  height:0px;\n"
"  subcontrol-position:right;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"  background:none;\n"
"  height:0px;\n"
"  subcontrol-position:left;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar:horizontal{\n"
"  background:palette(base);\n"
"  height:16px;\n"
"  margin:0px;\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"  background-color:palette(alternate-base);\n"
"  border-radius:2px;\n"
"  min-width:20px;\n"
"  margin:4px 2px 4px 2px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"  background-color:palette(highlight);\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"  background:none;\n"
"  width:0px;\n"
"  subcontrol-position:bottom;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"  background:none;\n"
"  width:0px;\n"
"  subcontrol-position:top;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QSlider::handle:horizontal{\n"
"  border-radius:4px;\n"
"  border:1px solid rgba(25,25,25,255);\n"
"  background-color:palette(alternate-base);\n"
"  min-height:20px;\n"
"  margin:0 -4px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"  background:palette(highlight);\n"
"}\n"
"QSlider::add-page:horizontal{\n"
"  background:palette(base);\n"
"}\n"
"QSlider::sub-page:horizontal{\n"
"  background:palette(highlight);\n"
"}\n"
"QSlider::sub-page:horizontal:disabled{\n"
"  background:rgb(80,80,80);\n"
"}")
        self.lineEdit_license_plate.setObjectName("lineEdit_license_plate")
        self.horizontalLayout.addWidget(self.lineEdit_license_plate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_location = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_location.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_location.setAutoFillBackground(False)
        self.lineEdit_location.setStyleSheet("QLineEdit{\n"
"background-color:rgb(170, 170, 170)\n"
"}\n"
"QToolTip{\n"
"  color:#ffffff;\n"
"  background-color:palette(base);\n"
"  border:1px solid palette(highlight);\n"
"  border-radius:4px;\n"
"}\n"
"QStatusBar{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  color:palette(mid);\n"
"}\n"
"QMenuBar{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-bottom:2px solid rgba(25,25,25,75);\n"
"}\n"
"QMenuBar::item{\n"
"  spacing:2px;\n"
"  padding:3px 4px;\n"
"  background:transparent;\n"
"}\n"
"QMenuBar::item:selected{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(106,106,106,255),stop:1 rgba(106,106,106,75));\n"
"  border-left:1px solid rgba(106,106,106,127);\n"
"  border-right:1px solid rgba(106,106,106,127);\n"
"}\n"
"QMenuBar::item:pressed{\n"
"  background-color:palette(highlight);\n"
"  border-left:1px solid rgba(25,25,25,127);\n"
"  border-right:1px solid rgba(25,25,25,127);\n"
"}\n"
"QMenu{\n"
"  background-color:palette(window);\n"
"  border:1px solid palette(shadow);\n"
"}\n"
"QMenu::item{\n"
"  padding:3px 25px 3px 25px;\n"
"  border:1px solid transparent;\n"
"}\n"
"QMenu::item:disabled{\n"
"  background-color:rgba(35,35,35,127);\n"
"  color:palette(disabled);\n"
"}\n"
"QMenu::item:selected{\n"
"  border-color:rgba(147,191,236,127);\n"
"  background:palette(highlight);\n"
"}\n"
"QMenu::icon:checked{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid palette(highlight);\n"
"  border-radius:2px;\n"
"}\n"
"QMenu::separator{\n"
"  height:1px;\n"
"  background:palette(alternate-base);\n"
"  margin-left:5px;\n"
"  margin-right:5px;\n"
"}\n"
"QMenu::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QMenu::indicator:non-exclusive:checked{\n"
"  image:url(:/darkstyle/icon_checkbox_checked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:non-exclusive:unchecked{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:exclusive:checked{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:exclusive:unchecked{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QToolBar::top{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-bottom:3px solid qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::bottom{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-top:3px solid qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::left{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-right:3px solid qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::right{\n"
"  background-color:qlineargradient(x1:1,y1:0,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-left:3px solid qlineargradient(x1:1,y1:0,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QMainWindow::separator{\n"
"  width:6px;\n"
"  height:5px;\n"
"  padding:2px;\n"
"}\n"
"QSplitter::handle:horizontal{\n"
"  width:10px;\n"
"}\n"
"QSplitter::handle:vertical{\n"
"  height:10px;\n"
"}\n"
"QMainWindow::separator:hover,QSplitter::handle:hover{\n"
"  background:palette(highlight);\n"
"}\n"
"QDockWidget::title{\n"
"  padding:4px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-bottom:2px solid rgba(25,25,25,75);\n"
"}\n"
"QDockWidget{\n"
"  titlebar-close-icon:url(:/darkstyle/icon_close.png);\n"
"  titlebar-normal-icon:url(:/darkstyle/icon_restore.png);\n"
"}\n"
"QDockWidget::close-button,QDockWidget::float-button{\n"
"  subcontrol-position:top right;\n"
"  subcontrol-origin:margin;\n"
"  position:absolute;\n"
"  top:3px;\n"
"  bottom:0px;\n"
"  width:20px;\n"
"  height:20px;\n"
"}\n"
"QDockWidget::close-button{\n"
"  right:3px;\n"
"}\n"
"QDockWidget::float-button{\n"
"  right:25px;\n"
"}\n"
"QGroupBox{\n"
"  background-color:rgba(66,66,66,50%);\n"
"  margin-top:27px;\n"
"  border:1px solid rgba(25,25,25,127);\n"
"  border-radius:4px;\n"
"}\n"
"QGroupBox::title{\n"
"  subcontrol-origin:margin;\n"
"  subcontrol-position:left top;\n"
"  padding:4px 6px;\n"
"  margin-left:3px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-bottom:2px solid rgb(127,127,127);\n"
"  border-top-left-radius:4px;\n"
"  border-top-right-radius:4px;\n"
"}\n"
"QTabWidget::pane{\n"
"  background-color:rgba(66,66,66,50%);\n"
"  border-top:1px solid rgba(25,25,25,50%);\n"
"}\n"
"QTabWidget::tab-bar{\n"
"  left:3px;\n"
"  top:1px;\n"
"}\n"
"QTabBar{\n"
"  background-color:transparent;\n"
"  qproperty-drawBase:0;\n"
"  border-bottom:1px solid rgba(25,25,25,50%);\n"
"}\n"
"QTabBar::tab{\n"
"  padding:4px 6px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-top-left-radius:4px;\n"
"  border-top-right-radius:4px;\n"
"}\n"
"QTabBar::tab:selected,QTabBar::tab:hover{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(53,53,53,127),stop:1 rgba(66,66,66,50%));\n"
"  border-bottom-color:rgba(66,66,66,75%);\n"
"}\n"
"QTabBar::tab:selected{\n"
"  border-bottom:2px solid palette(highlight);\n"
"}\n"
"QTabBar::tab::selected:disabled{\n"
"  border-bottom:2px solid rgb(127,127,127);\n"
"}\n"
"QTabBar::tab:!selected{\n"
"  margin-top:2px;\n"
"}\n"
"QCheckBox::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QCheckBox::indicator:checked,QTreeView::indicator:checked,QTableView::indicator:checked,QGroupBox::indicator:checked{\n"
"  image:url(:/darkstyle/icon_checkbox_checked.png);\n"
"}\n"
"QCheckBox::indicator:checked:pressed,QTreeView::indicator:checked:pressed,QTableView::indicator:checked:pressed,QGroupBox::indicator:checked:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_checked_pressed.png);\n"
"}\n"
"QCheckBox::indicator:checked:disabled,QTreeView::indicator:checked:disabled,QTableView::indicator:checked:disabled,QGroupBox::indicator:checked:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_checked_disabled.png);\n"
"}\n"
"QCheckBox::indicator:unchecked,QTreeView::indicator:unchecked,QTableView::indicator:unchecked,QGroupBox::indicator:unchecked{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked.png);\n"
"}\n"
"QCheckBox::indicator:unchecked:pressed,QTreeView::indicator:unchecked:pressed,QTableView::indicator:unchecked:pressed,QGroupBox::indicator:unchecked:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked_pressed.png);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled,QTreeView::indicator:unchecked:disabled,QTableView::indicator:unchecked:disabled,QGroupBox::indicator:unchecked:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked_disabled.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate,QTreeView::indicator:indeterminate,QTableView::indicator:indeterminate,QGroupBox::indicator:indeterminate{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate:pressed,QTreeView::indicator:indeterminate:pressed,QTableView::indicator:indeterminate:pressed,QGroupBox::indicator:indeterminate:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate_pressed.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate:disabled,QTreeView::indicator:indeterminate:disabled,QTableView::indicator:indeterminate:disabled,QGroupBox::indicator:indeterminate:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate_disabled.png);\n"
"}\n"
"QRadioButton::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked.png);\n"
"}\n"
"QRadioButton::indicator:checked:pressed{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked_pressed.png);\n"
"}\n"
"QRadioButton::indicator:checked:disabled{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked_disabled.png);\n"
"}\n"
"QRadioButton::indicator:unchecked{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked.png);\n"
"}\n"
"QRadioButton::indicator:unchecked:pressed{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked_pressed.png);\n"
"}\n"
"QRadioButton::indicator:unchecked:disabled{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked_disabled.png);\n"
"}\n"
"QTreeView, QTableView{\n"
"  alternate-background-color:palette(window);\n"
"  background:palette(base);\n"
"}\n"
"QTreeView QHeaderView::section, QTableView QHeaderView::section{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-style:none;\n"
"  border-bottom:1px solid palette(dark);\n"
"  padding-left:5px;\n"
"  padding-right:5px;\n"
"}\n"
"QTreeView::item:selected:disabled, QTableView::item:selected:disabled{\n"
"  background:rgb(80,80,80);\n"
"}\n"
"QTreeView::branch{\n"
"  background-color:palette(base);\n"
"}\n"
"QTreeView::branch:has-siblings:!adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_vline.png) 0;\n"
"}\n"
"QTreeView::branch:has-siblings:adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_branch_more.png) 0;\n"
"}\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_branch_end.png) 0;\n"
"}\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings{\n"
"  border-image:none;\n"
"  image:url(:/darkstyle/icon_branch_closed.png);\n"
"}\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings{\n"
"  border-image:none;\n"
"  image:url(:/darkstyle/icon_branch_open.png);\n"
"}\n"
"QScrollBar:vertical{\n"
"  background:palette(base);\n"
"  border-top-right-radius:2px;\n"
"  border-bottom-right-radius:2px;\n"
"  width:16px;\n"
"  margin:0px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"  background-color:palette(alternate-base);\n"
"  border-radius:2px;\n"
"  min-height:20px;\n"
"  margin:2px 4px 2px 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"  background-color:palette(highlight);\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"  background:none;\n"
"  height:0px;\n"
"  subcontrol-position:right;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"  background:none;\n"
"  height:0px;\n"
"  subcontrol-position:left;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar:horizontal{\n"
"  background:palette(base);\n"
"  height:16px;\n"
"  margin:0px;\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"  background-color:palette(alternate-base);\n"
"  border-radius:2px;\n"
"  min-width:20px;\n"
"  margin:4px 2px 4px 2px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"  background-color:palette(highlight);\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"  background:none;\n"
"  width:0px;\n"
"  subcontrol-position:bottom;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"  background:none;\n"
"  width:0px;\n"
"  subcontrol-position:top;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QSlider::handle:horizontal{\n"
"  border-radius:4px;\n"
"  border:1px solid rgba(25,25,25,255);\n"
"  background-color:palette(alternate-base);\n"
"  min-height:20px;\n"
"  margin:0 -4px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"  background:palette(highlight);\n"
"}\n"
"QSlider::add-page:horizontal{\n"
"  background:palette(base);\n"
"}\n"
"QSlider::sub-page:horizontal{\n"
"  background:palette(highlight);\n"
"}\n"
"QSlider::sub-page:horizontal:disabled{\n"
"  background:rgb(80,80,80);\n"
"}")
        self.lineEdit_location.setObjectName("lineEdit_location")
        self.horizontalLayout_3.addWidget(self.lineEdit_location)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_time = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_time.setAutoFillBackground(False)
        self.lineEdit_time.setStyleSheet("QLineEdit{\n"
"background-color:rgb(170, 170, 170)\n"
"}\n"
"QToolTip{\n"
"  color:#ffffff;\n"
"  background-color:palette(base);\n"
"  border:1px solid palette(highlight);\n"
"  border-radius:4px;\n"
"}\n"
"QStatusBar{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  color:palette(mid);\n"
"}\n"
"QMenuBar{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-bottom:2px solid rgba(25,25,25,75);\n"
"}\n"
"QMenuBar::item{\n"
"  spacing:2px;\n"
"  padding:3px 4px;\n"
"  background:transparent;\n"
"}\n"
"QMenuBar::item:selected{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(106,106,106,255),stop:1 rgba(106,106,106,75));\n"
"  border-left:1px solid rgba(106,106,106,127);\n"
"  border-right:1px solid rgba(106,106,106,127);\n"
"}\n"
"QMenuBar::item:pressed{\n"
"  background-color:palette(highlight);\n"
"  border-left:1px solid rgba(25,25,25,127);\n"
"  border-right:1px solid rgba(25,25,25,127);\n"
"}\n"
"QMenu{\n"
"  background-color:palette(window);\n"
"  border:1px solid palette(shadow);\n"
"}\n"
"QMenu::item{\n"
"  padding:3px 25px 3px 25px;\n"
"  border:1px solid transparent;\n"
"}\n"
"QMenu::item:disabled{\n"
"  background-color:rgba(35,35,35,127);\n"
"  color:palette(disabled);\n"
"}\n"
"QMenu::item:selected{\n"
"  border-color:rgba(147,191,236,127);\n"
"  background:palette(highlight);\n"
"}\n"
"QMenu::icon:checked{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid palette(highlight);\n"
"  border-radius:2px;\n"
"}\n"
"QMenu::separator{\n"
"  height:1px;\n"
"  background:palette(alternate-base);\n"
"  margin-left:5px;\n"
"  margin-right:5px;\n"
"}\n"
"QMenu::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QMenu::indicator:non-exclusive:checked{\n"
"  image:url(:/darkstyle/icon_checkbox_checked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:non-exclusive:unchecked{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:exclusive:checked{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QMenu::indicator:exclusive:unchecked{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked.png);\n"
"  padding-left:2px;\n"
"}\n"
"QToolBar::top{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-bottom:3px solid qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::bottom{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-top:3px solid qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::left{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-right:3px solid qlineargradient(x1:0,y1:0,x2:1,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QToolBar::right{\n"
"  background-color:qlineargradient(x1:1,y1:0,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-left:3px solid qlineargradient(x1:1,y1:0,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"}\n"
"QMainWindow::separator{\n"
"  width:6px;\n"
"  height:5px;\n"
"  padding:2px;\n"
"}\n"
"QSplitter::handle:horizontal{\n"
"  width:10px;\n"
"}\n"
"QSplitter::handle:vertical{\n"
"  height:10px;\n"
"}\n"
"QMainWindow::separator:hover,QSplitter::handle:hover{\n"
"  background:palette(highlight);\n"
"}\n"
"QDockWidget::title{\n"
"  padding:4px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-bottom:2px solid rgba(25,25,25,75);\n"
"}\n"
"QDockWidget{\n"
"  titlebar-close-icon:url(:/darkstyle/icon_close.png);\n"
"  titlebar-normal-icon:url(:/darkstyle/icon_restore.png);\n"
"}\n"
"QDockWidget::close-button,QDockWidget::float-button{\n"
"  subcontrol-position:top right;\n"
"  subcontrol-origin:margin;\n"
"  position:absolute;\n"
"  top:3px;\n"
"  bottom:0px;\n"
"  width:20px;\n"
"  height:20px;\n"
"}\n"
"QDockWidget::close-button{\n"
"  right:3px;\n"
"}\n"
"QDockWidget::float-button{\n"
"  right:25px;\n"
"}\n"
"QGroupBox{\n"
"  background-color:rgba(66,66,66,50%);\n"
"  margin-top:27px;\n"
"  border:1px solid rgba(25,25,25,127);\n"
"  border-radius:4px;\n"
"}\n"
"QGroupBox::title{\n"
"  subcontrol-origin:margin;\n"
"  subcontrol-position:left top;\n"
"  padding:4px 6px;\n"
"  margin-left:3px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-bottom:2px solid rgb(127,127,127);\n"
"  border-top-left-radius:4px;\n"
"  border-top-right-radius:4px;\n"
"}\n"
"QTabWidget::pane{\n"
"  background-color:rgba(66,66,66,50%);\n"
"  border-top:1px solid rgba(25,25,25,50%);\n"
"}\n"
"QTabWidget::tab-bar{\n"
"  left:3px;\n"
"  top:1px;\n"
"}\n"
"QTabBar{\n"
"  background-color:transparent;\n"
"  qproperty-drawBase:0;\n"
"  border-bottom:1px solid rgba(25,25,25,50%);\n"
"}\n"
"QTabBar::tab{\n"
"  padding:4px 6px;\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border:1px solid rgba(25,25,25,75);\n"
"  border-top-left-radius:4px;\n"
"  border-top-right-radius:4px;\n"
"}\n"
"QTabBar::tab:selected,QTabBar::tab:hover{\n"
"  background-color:qlineargradient(x1:0,y1:0,x2:0,y2:1,stop:0 rgba(53,53,53,127),stop:1 rgba(66,66,66,50%));\n"
"  border-bottom-color:rgba(66,66,66,75%);\n"
"}\n"
"QTabBar::tab:selected{\n"
"  border-bottom:2px solid palette(highlight);\n"
"}\n"
"QTabBar::tab::selected:disabled{\n"
"  border-bottom:2px solid rgb(127,127,127);\n"
"}\n"
"QTabBar::tab:!selected{\n"
"  margin-top:2px;\n"
"}\n"
"QCheckBox::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QCheckBox::indicator:checked,QTreeView::indicator:checked,QTableView::indicator:checked,QGroupBox::indicator:checked{\n"
"  image:url(:/darkstyle/icon_checkbox_checked.png);\n"
"}\n"
"QCheckBox::indicator:checked:pressed,QTreeView::indicator:checked:pressed,QTableView::indicator:checked:pressed,QGroupBox::indicator:checked:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_checked_pressed.png);\n"
"}\n"
"QCheckBox::indicator:checked:disabled,QTreeView::indicator:checked:disabled,QTableView::indicator:checked:disabled,QGroupBox::indicator:checked:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_checked_disabled.png);\n"
"}\n"
"QCheckBox::indicator:unchecked,QTreeView::indicator:unchecked,QTableView::indicator:unchecked,QGroupBox::indicator:unchecked{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked.png);\n"
"}\n"
"QCheckBox::indicator:unchecked:pressed,QTreeView::indicator:unchecked:pressed,QTableView::indicator:unchecked:pressed,QGroupBox::indicator:unchecked:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked_pressed.png);\n"
"}\n"
"QCheckBox::indicator:unchecked:disabled,QTreeView::indicator:unchecked:disabled,QTableView::indicator:unchecked:disabled,QGroupBox::indicator:unchecked:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_unchecked_disabled.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate,QTreeView::indicator:indeterminate,QTableView::indicator:indeterminate,QGroupBox::indicator:indeterminate{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate:pressed,QTreeView::indicator:indeterminate:pressed,QTableView::indicator:indeterminate:pressed,QGroupBox::indicator:indeterminate:pressed{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate_pressed.png);\n"
"}\n"
"QCheckBox::indicator:indeterminate:disabled,QTreeView::indicator:indeterminate:disabled,QTableView::indicator:indeterminate:disabled,QGroupBox::indicator:indeterminate:disabled{\n"
"  image:url(:/darkstyle/icon_checkbox_indeterminate_disabled.png);\n"
"}\n"
"QRadioButton::indicator{\n"
"  width:18px;\n"
"  height:18px;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked.png);\n"
"}\n"
"QRadioButton::indicator:checked:pressed{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked_pressed.png);\n"
"}\n"
"QRadioButton::indicator:checked:disabled{\n"
"  image:url(:/darkstyle/icon_radiobutton_checked_disabled.png);\n"
"}\n"
"QRadioButton::indicator:unchecked{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked.png);\n"
"}\n"
"QRadioButton::indicator:unchecked:pressed{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked_pressed.png);\n"
"}\n"
"QRadioButton::indicator:unchecked:disabled{\n"
"  image:url(:/darkstyle/icon_radiobutton_unchecked_disabled.png);\n"
"}\n"
"QTreeView, QTableView{\n"
"  alternate-background-color:palette(window);\n"
"  background:palette(base);\n"
"}\n"
"QTreeView QHeaderView::section, QTableView QHeaderView::section{\n"
"  background-color:qlineargradient(x1:0,y1:1,x2:0,y2:0,stop:0 rgba(25,25,25,127),stop:1 rgba(53,53,53,75));\n"
"  border-style:none;\n"
"  border-bottom:1px solid palette(dark);\n"
"  padding-left:5px;\n"
"  padding-right:5px;\n"
"}\n"
"QTreeView::item:selected:disabled, QTableView::item:selected:disabled{\n"
"  background:rgb(80,80,80);\n"
"}\n"
"QTreeView::branch{\n"
"  background-color:palette(base);\n"
"}\n"
"QTreeView::branch:has-siblings:!adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_vline.png) 0;\n"
"}\n"
"QTreeView::branch:has-siblings:adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_branch_more.png) 0;\n"
"}\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item{\n"
"  border-image:url(:/darkstyle/icon_branch_end.png) 0;\n"
"}\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings{\n"
"  border-image:none;\n"
"  image:url(:/darkstyle/icon_branch_closed.png);\n"
"}\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings{\n"
"  border-image:none;\n"
"  image:url(:/darkstyle/icon_branch_open.png);\n"
"}\n"
"QScrollBar:vertical{\n"
"  background:palette(base);\n"
"  border-top-right-radius:2px;\n"
"  border-bottom-right-radius:2px;\n"
"  width:16px;\n"
"  margin:0px;\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"  background-color:palette(alternate-base);\n"
"  border-radius:2px;\n"
"  min-height:20px;\n"
"  margin:2px 4px 2px 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"  background-color:palette(highlight);\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"  background:none;\n"
"  height:0px;\n"
"  subcontrol-position:right;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"  background:none;\n"
"  height:0px;\n"
"  subcontrol-position:left;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar:horizontal{\n"
"  background:palette(base);\n"
"  height:16px;\n"
"  margin:0px;\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"  background-color:palette(alternate-base);\n"
"  border-radius:2px;\n"
"  min-width:20px;\n"
"  margin:4px 2px 4px 2px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"  background-color:palette(highlight);\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"  background:none;\n"
"  width:0px;\n"
"  subcontrol-position:bottom;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"  background:none;\n"
"  width:0px;\n"
"  subcontrol-position:top;\n"
"  subcontrol-origin:margin;\n"
"}\n"
"QSlider::handle:horizontal{\n"
"  border-radius:4px;\n"
"  border:1px solid rgba(25,25,25,255);\n"
"  background-color:palette(alternate-base);\n"
"  min-height:20px;\n"
"  margin:0 -4px;\n"
"}\n"
"QSlider::handle:horizontal:hover{\n"
"  background:palette(highlight);\n"
"}\n"
"QSlider::add-page:horizontal{\n"
"  background:palette(base);\n"
"}\n"
"QSlider::sub-page:horizontal{\n"
"  background:palette(highlight);\n"
"}\n"
"QSlider::sub-page:horizontal:disabled{\n"
"  background:rgb(80,80,80);\n"
"}")
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.horizontalLayout_2.addWidget(self.lineEdit_time)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(40, 290, 201, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_accept = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_accept.setFont(font)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout_5.addWidget(self.pushButton_accept)
        self.pushButton_deny = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_deny.setFont(font)
        self.pushButton_deny.setObjectName("pushButton_deny")
        self.horizontalLayout_5.addWidget(self.pushButton_deny)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(300, 60, 201, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 201, 241))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "TICKET INFORMATIN"))
        self.label_4.setText(_translate("MainWindow", "REPORT NUMBER"))
        self.label1.setText(_translate("MainWindow", "LICENSE PLATE NUMBER"))
        self.label_2.setText(_translate("MainWindow", "LOCATION"))
        self.label.setText(_translate("MainWindow", "TIME"))
        self.pushButton_accept.setText(_translate("MainWindow", "ACCEPT"))
        self.pushButton_deny.setText(_translate("MainWindow", "DENY"))
        self.groupBox_2.setTitle(_translate("MainWindow", "IMAGE"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
